Repository eli-halych/CoPrevent, pull requests merged in 2020-06, with the labels that each got.

#9 add statistics
  .DS_Store
  Procfile
  backend/app.py
  backend/data/Global_Mobility_Report2.csv
  backend/main.py
  backend/scripts/__init__.py
  backend/scripts/searches.py
  backend/scripts/table.py
  frontend/.DS_Store
  frontend/static/mainStyle.css
  frontend/templates/world.html
  requirements.txt
Labels: enhancement

#11 update css for graph
  frontend/static/mainStyle.css
Labels: bug, enhancement

#12 Fixed styles for Bokeh graph
  frontend/static/mainStyle.css
  frontend/templates/world.html
Labels: bug, enhancement

#13 Update ReadMe
  README.md
Labels: documentation

#14 Section CSS: heights and width
  .DS_Store
  Procfile
  README.md
  backend/app.py
  backend/data/Global_Mobility_Report2.csv
  backend/main.py
  backend/scripts/__init__.py
  backend/scripts/searches.py
  backend/scripts/table.py
  frontend/.DS_Store
  frontend/static/js/world.js
  frontend/static/mainStyle.css
  frontend/templates/world.html
  requirements.txt
Labels: bug, documentation, enhancement
